### ISSUE TITLE
AutoSave 

### ISSUE THREAD

**Issue by thejohnd0e** [ilian6806/stable-diffusion-webui-state#60]
Dosn't retain AutoSave status after restart.

**Comment by VL4DST3R** [comment]
I stopped using this extension due to all the bugs and inconsistency of saving. I recommend you try https://github.com/SenshiSentou/sd-webui-state-manager as an alternative, as this one seems to be dead. Sadly it does not auto-populate the settings at first load like this one did but you get much more granular control and a prompt history.

**Comment by ilian6806** [comment]
I can try to add this if you show me where it is in the UI.

**Comment by VL4DST3R** [comment]
Not op but I figured maybe I can help; I think he is referring to the actual checkboxes this extension provides within settings to configure what you want restored - not getting saved properly, although I can't reproduce this on my end.

**Comment by ilian6806** [comment]
Seems to be working fine now.
